[package]
name = "fast_async_trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_async_trait_proc = { path = "proc", version = "0.1.0" }

[workspace]
members = ["proc"]